#ktor:
#  application:
#    modules:
#      - app.QRventure.ApplicationKt.module
#  deployment:
#    host: 0.0.0.0
#    port: 8020
#postgres:
#  url: "jdbc:postgresql://localhost:5434/qrventure_db"
#  user: "postgres"
#  password: "root"
#  required: true

ktor:
  application:
   modules:
     - app.QRventure.ApplicationKt.module
 deployment:
    port: ${PORT:8080}  # Render sets PORT; fall back to 8080 locally
database:
  driver: "org.postgresql.Driver"
  url: ${JDBC_DATABASE_URL}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
