ktor {
  application {
    modules = [ app.QRventure.ApplicationKt.module ]
  }
  deployment {
    host = "0.0.0.0"
    port = 8020
  }
}

postgres {
  url = "jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require"
  url = ${?POSTGRES_URL}
  user = "postgres.mgguubobmehctoygbglc"
  user = ${?POSTGRES_USER}
  password = "yUb7RlA9jUaPSd7Q"
  password = ${?POSTGRES_PASSWORD}
  required = true
}
